name-template: 'Version $RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🚨 Dependencies'
    label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'type: major'
  minor:
    labels:
      - 'type: minor'
  patch:
    labels:
      - 'type: patch'
  default: patch
template: |
  ## Changes

  $CHANGES
