name: Print Variables

on:
  push:
    tags:
      - '*'
    branches:
      - '**'

jobs:
  print:
    name: Printing
    runs-on: ubuntu-latest

    steps:
      - run: echo '${{ toJSON(github) }}'
