name: Release

on:
  repository_dispatch:
    types: [create_release]

jobs:
  update_release_draft:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@add-release-output

  update_readme:
    needs: [update_release_draft]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Find and Replace old versions
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "(v[0-9].[0-9].[0-9])"
          replace: ${{ needs.update_release_draft.outputs.tag_name }}
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          default_author: user_info
          message: 'bump readme versions'
          push: origin main --force

  create_release:
    needs: [update_readme]
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@add-release-output
    with:
      publish: true
