# Do not change this name, because workflows reference each other by it.
name: Release Production

env:
  IMAGE_NAME: private/backend

# Description
#
# This workflow creates a production release. It is only creating the release
# if the tag has the required tag format, please use ./createRelease.sh to create
# such tags.
# The workflow is only successful if for the same commit of the Tag, a "Tests"
# workflow finished successfully. If this workflow was triggered before the Tests
# were completed, there is a "Rerun Production Release" workflow, which restarts
# the production release workflow (if any exists) after the tests completed.

on:
  push:
    tags: [ '**' ]

jobs:
  create_production_release:
    name: Release Production
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: nonsence
        run: echo "Hello World"

      - name: test
        id: query_workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo ::set-output name=tests_completed::false

      - name: login to registry
        if: steps.query_workflows.outputs.tests_completed == 'true'
        uses: docker/login-action@v1
        run: echo "other test"

  second:
    needs: [ first ]
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@v1.1.0
