name: Release Production

on:
  push:

jobs:
  first:
    name: Release Production
    runs-on: ubuntu-latest

    outputs:
      tests_completed: ${{ steps.query_workflows.outputs.tests_completed }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: nonsence
        run: echo "Hello World"

      - name: test
        id: query_workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo ::set-output name=tests_completed::true

      - name: login to registry
        if: steps.query_workflows.outputs.tests_completed == 'true'
        run: echo "other test"

  second:
    needs: [ first ]
    if: needs.first.outputs.tests_completed == 'true'
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@v1.1.0
