name: YAMLlint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  yamllint:

    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo "Hello World"

      - uses: Staffbase/gha-workflows/.github/workflows/template_yaml.yml@main
